version: '3.9'

services:

  db:
    image: mysql:8.0.33
    ports:
      - "3306:3306"
   
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: businiss_manage
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    volumes:
      - /Users/truongthanhtung/Documents/wordSpace/businiss_management/data/mysql:/var/lib/mysql

   